### PR TITLE
Decoder caps negotiation

### PR DESCRIPTION
**Pull request by ceyusa**

### CODE REVIEW

**Comment by uartie** [comment]
All vp9 decode test failures, for example:
```
[2020-05-26 15:41:08.281629] DEBUG: slash: CALL: gst-launch-1.0 -vf filesrc location=/opt/media/src/assets/otc-media/vp9/8bit/g2_decoder_case_14000.webm ! matroskademux ! vaapivp9dec ! videoconvert dither=0 ! video/x-raw,format=I420 ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=/opt/media/test-results/vaapi-fits/gst-vaapi-iHD/413179f8-9f67-11ea-a487-0242ac110002_0/_0.test.gst-vaapi.decode.vp9/default/g2_decoder_case_14000_352x288_I420.yuv (pid: 17503)
[2020-05-26 15:41:08.327510] DEBUG: slash: Setting pipeline to PAUSED ...
[2020-05-26 15:41:08.343615] DEBUG: slash: Pipeline is PREROLLING ...
[2020-05-26 15:41:08.343745] DEBUG: slash: Got context from element 'vaapidecode_vp9-0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayEGL\)\ gldisplayegl0";
[2020-05-26 15:41:08.343796] DEBUG: slash: Got context from element 'vaapidecode_vp9-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
[2020-05-26 15:41:08.344918] DEBUG: slash: /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0.GstPad:sink: caps = video/x-vp9, width=(int)352, height=(int)288, framerate=(fraction)15712927/524288
[2020-05-26 15:41:08.345628] DEBUG: slash: ERROR: from element /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0: No valid frames decoded before end of stream
[2020-05-26 15:41:08.345693] DEBUG: slash: Additional debug info:
[2020-05-26 15:41:08.345738] DEBUG: slash: ../gst-libs/gst/video/gstvideodecoder.c(1207): gst_video_decoder_sink_event_default (): /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0:
[2020-05-26 15:41:08.346608] DEBUG: slash: no valid frames found
[2020-05-26 15:41:08.346799] DEBUG: slash: ERROR: pipeline doesn't want to preroll.
[2020-05-26 15:41:08.346933] DEBUG: slash: Setting pipeline to NULL ...
[2020-05-26 15:41:08.359743] DEBUG: slash: Freeing pipeline ...
[2020-05-26 15:41:08.365563] INFO: slash: DETAIL: time(gst:1) = 0.0876s
[2020-05-26 15:41:08.371531] TRACE: slash.core.error: Error added: AssertionError: CALL ERROR: failed with exitcode 1 (pid: 17503)
```

**Comment by ceyusa** [comment]
mmmh.. it works with i965 but not with iHD

**Comment by ceyusa** [comment]
It's choosing VAProfileVP9Profile3 which doesn's exist in my hardware and thus unable to expose a proper color format.

**Comment by uartie** [comment]
The Intel CI will continuously re-check open PR's when upstream dependencies change (e.g. libva, driver's, ...).  I am closing this for now to save on CI resources.  Feel free to reopen/resubmit if you plan to push a new update to this PR and need another round of CI checks.  Cheers.

**Pull request closed without merging**
