### PR TITLE
Decoder caps negotiation

### PR DESCRIPTION
**Pull request by ceyusa**
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/merge_requests/265

### CODE REVIEW

**Comment by ceyusa** [comment]
I would like to know what failed :)

**Comment by uartie** [comment]
iHD vp9 10bit decode is failing because SSIM < 1.0.  That is, the decoded result does not bitmatch the expected reference output.

```
[2020-04-08 19:55:35.268981] NOTICE: slash: DETAIL: case = vp9_PU32x32_NEAREST_10bit_fastfood_64x64
[2020-04-08 19:55:35.357673] INFO: slash: CALL: gst-launch-1.0 -vf filesrc location=/opt/media/src/assets/otc-media/vp9/10bit/vp9_PU32x32_NEAREST_10bit_fastfood_64x64.ivf ! ivfparse ! vaapivp9dec ! videoconvert dither=0 ! video/x-raw,format=P010_10LE ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=/opt/media/test-results/vaapi-fits/gst-vaapi-iHD/bf89261c-79d2-11ea-b360-0242ac110002_0/_0.test.gst-vaapi.decode.10bit.vp9/default/vp9_PU32x32_NEAREST_10bit_fastfood_64x64_64x64_P010.yuv (pid: 17653)
[2020-04-08 19:55:35.367481] INFO: slash: DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2020-04-08 19:55:35.367696] INFO: slash: Assuming 131072kB available aperture size.
[2020-04-08 19:55:35.367896] INFO: slash: May lead to reduced performance or incorrect rendering.
[2020-04-08 19:55:35.368023] INFO: slash: get chip id failed: -1 [2]
[2020-04-08 19:55:35.368144] INFO: slash: param: 4, val: 0
[2020-04-08 19:55:35.395022] INFO: slash: Setting pipeline to PAUSED ...
[2020-04-08 19:55:35.398295] INFO: slash: DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2020-04-08 19:55:35.398593] INFO: slash: Assuming 131072kB available aperture size.
[2020-04-08 19:55:35.398875] INFO: slash: May lead to reduced performance or incorrect rendering.
[2020-04-08 19:55:35.399081] INFO: slash: get chip id failed: -1 [2]
[2020-04-08 19:55:35.399295] INFO: slash: param: 4, val: 0
[2020-04-08 19:55:35.401649] INFO: slash: Pipeline is PREROLLING ...
[2020-04-08 19:55:35.402063] INFO: slash: Got context from element 'vaapidecode_vp9-0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayEGL\)\ gldisplayegl0";
[2020-04-08 19:55:35.402452] INFO: slash: Got context from element 'vaapidecode_vp9-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
[2020-04-08 19:55:35.402800] INFO: slash: /GstPipeline:pipeline0/GstIvfParse:ivfparse0.GstPad:src: caps = video/x-vp9, width=(int)64, height=(int)64, framerate=(fraction)1000/1
[2020-04-08 19:55:35.403767] INFO: slash: /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0.GstPad:sink: caps = video/x-vp9, width=(int)64, height=(int)64, framerate=(fraction)1000/1
[2020-04-08 19:55:35.405594] INFO: slash: Redistribute latency...
[2020-04-08 19:55:35.406425] INFO: slash: /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0.GstPad:src: caps = video/x-raw, format=(string)NV12, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 19:55:35.407160] INFO: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:src: caps = video/x-raw, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)1000/1, format=(string)P010_10LE
[2020-04-08 19:55:35.407878] INFO: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = video/x-raw, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)1000/1, format=(string)P010_10LE
[2020-04-08 19:55:35.408633] INFO: slash: /GstPipeline:pipeline0/GstCksumImageSink:cksumimagesink0.GstPad:sink: caps = video/x-raw, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)1000/1, format=(string)P010_10LE
[2020-04-08 19:55:35.409360] INFO: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:sink: caps = video/x-raw, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)1000/1, format=(string)P010_10LE
[2020-04-08 19:55:35.410137] INFO: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:sink: caps = video/x-raw, format=(string)NV12, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 19:55:35.415035] INFO: slash: Pipeline is PREROLLED ...
[2020-04-08 19:55:35.415322] INFO: slash: Setting pipeline to PLAYING ...
[2020-04-08 19:55:35.415576] INFO: slash: New clock: GstSystemClock
[2020-04-08 19:55:35.416998] INFO: slash: Got EOS from element "pipeline0".
[2020-04-08 19:55:35.417288] INFO: slash: Execution ended after 0:00:00.001975096
[2020-04-08 19:55:35.417530] INFO: slash: Setting pipeline to NULL ...
[2020-04-08 19:55:35.424924] INFO: slash: Freeing pipeline ...
[2020-04-08 19:55:35.492447] NOTICE: slash: DETAIL: time(gst:1) = 0.1386s
[2020-04-08 19:55:35.495902] NOTICE: slash: DETAIL: time(ssim:1) = 0.0029s
[2020-04-08 19:55:35.496263] NOTICE: slash: DETAIL: ssim = [0.9998, 0.999, 0.999, 0.9998, 0.999, 0.999]
[2020-04-08 19:55:35.500207] TRACE: slash.core.error: Error added: AssertionError: assert 0.9998 >= 1.0
```

It looks like vaapidecode src caps are NV12 (but should be P010_10LE).  This causes the videoconvert element to be non-passthrough.  The conversion is causing pixel precision to be lost.

**Comment by uartie** [comment]
Before this change, iHD vp9 10bit decode use to produce this link chain:
```
[2020-04-08 20:03:28.414207] NOTICE: slash: DETAIL: case = vp9_PU32x32_NEAREST_10bit_fastfood_64x64
[2020-04-08 20:03:28.507535] INFO: slash: CALL: gst-launch-1.0 -vf filesrc location=/opt/media/src/assets/otc-media/vp9/10bit/vp9_PU32x32_NEAREST_10bit_fastfood_64x64.ivf ! ivfparse ! vaapivp9dec ! videoconvert dither=0 ! video/x-raw,format=P010_10LE ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=/opt/media/test-results/vaapi-fits/gst-vaapi-iHD/e37bf12a-79d3-11ea-901d-0242ac110002_0/_0.test.gst-vaapi.decode.10bit.vp9/default/vp9_PU32x32_NEAREST_10bit_fastfood_64x64_64x64_P010.yuv (pid: 17653)
[2020-04-08 20:03:28.517317] INFO: slash: DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2020-04-08 20:03:28.517543] INFO: slash: Assuming 131072kB available aperture size.
[2020-04-08 20:03:28.517668] INFO: slash: May lead to reduced performance or incorrect rendering.
[2020-04-08 20:03:28.517768] INFO: slash: get chip id failed: -1 [2]
[2020-04-08 20:03:28.517893] INFO: slash: param: 4, val: 0
[2020-04-08 20:03:28.522960] INFO: slash: Setting pipeline to PAUSED ...
[2020-04-08 20:03:28.524438] INFO: slash: DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2020-04-08 20:03:28.524587] INFO: slash: Assuming 131072kB available aperture size.
[2020-04-08 20:03:28.524756] INFO: slash: May lead to reduced performance or incorrect rendering.
[2020-04-08 20:03:28.524878] INFO: slash: get chip id failed: -1 [2]
[2020-04-08 20:03:28.524988] INFO: slash: param: 4, val: 0
[2020-04-08 20:03:28.535118] INFO: slash: Pipeline is PREROLLING ...
[2020-04-08 20:03:28.535293] INFO: slash: Got context from element 'vaapidecode_vp9-0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayEGL\)\ gldisplayegl0";
[2020-04-08 20:03:28.535450] INFO: slash: Got context from element 'vaapidecode_vp9-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
[2020-04-08 20:03:28.535594] INFO: slash: /GstPipeline:pipeline0/GstIvfParse:ivfparse0.GstPad:src: caps = video/x-vp9, width=(int)64, height=(int)64, framerate=(fraction)1000/1
[2020-04-08 20:03:28.535764] INFO: slash: /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0.GstPad:sink: caps = video/x-vp9, width=(int)64, height=(int)64, framerate=(fraction)1000/1
[2020-04-08 20:03:28.552199] INFO: slash: Redistribute latency...
[2020-04-08 20:03:28.552740] INFO: slash: /GstPipeline:pipeline0/GstVaapiDecode_vp9:vaapidecode_vp9-0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.553193] INFO: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.553554] INFO: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.553907] INFO: slash: /GstPipeline:pipeline0/GstCksumImageSink:cksumimagesink0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.554255] INFO: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.554598] INFO: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)64, height=(int)64, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)1000/1
[2020-04-08 20:03:28.554684] INFO: slash: Pipeline is PREROLLED ...
[2020-04-08 20:03:28.554793] INFO: slash: Setting pipeline to PLAYING ...
[2020-04-08 20:03:28.554885] INFO: slash: New clock: GstSystemClock
[2020-04-08 20:03:28.554982] INFO: slash: Got EOS from element "pipeline0".
[2020-04-08 20:03:28.555079] INFO: slash: Execution ended after 0:00:00.000494235
[2020-04-08 20:03:28.555174] INFO: slash: Setting pipeline to NULL ...
[2020-04-08 20:03:28.559622] INFO: slash: Freeing pipeline ...
[2020-04-08 20:03:28.577266] NOTICE: slash: DETAIL: time(gst:1) = 0.0736s
[2020-04-08 20:03:28.579289] NOTICE: slash: DETAIL: time(ssim:1) = 0.0017s
[2020-04-08 20:03:28.579497] NOTICE: slash: DETAIL: ssim = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[2020-04-08 20:03:28.717971] NOTICE: slash: DETAIL: time = 0.303539 seconds
```

**Comment by uartie** [comment]
On i965, there are similar failures in both vp9 and hevc 10bit decode.

**Comment by ceyusa** [comment]
Is the same error? 

I can't find media samples of vp9 profile 2 :/

**Comment by uartie** [comment]
> Is the same error?

No.  It looks like you fixed all of the vp9/hevc 10bit issues in your latest patches.

There is only 1 case failed now in i965 hevc encode (quality dropped).  It appears the failure is unrelated to your latest patches (same failure *without* your patches).  I will investigate what else caused that regression.  In the meantime, your patches don't regress any tests now and should be good  to submit to an upstream MR.

**Comment by uartie** [comment]
It appears the "baseparse: fix upstream read caching" patch in gstreamer is the cause of the test regression.

**Pull request closed without merging**
