### PR TITLE
vaapijpegenc: fix scaled quantization table

### PR DESCRIPTION
**Pull request by xhaihao**
Add 50 to match JPEG reference implementation. Also include the README
from the reference implementation.

### CODE REVIEW

**Comment by uartie** [comment]
@xhaihao what's the status here?  I assume this is meant to fix the issue where higher quality setting produces lower PSNR than some lower quality setting.  Did it work?  If so, then the slight PSNR drop for the test failures are expected, right?  And we just need to rebase the reference PSNR?

**Comment by xhaihao** [comment]
> @xhaihao what's the status here? I assume this is meant to fix the issue where higher quality setting produces lower PSNR than some lower quality setting. Did it work?

No, id doesn't fix this issue.  The root cause for this issue is still unknown.

> If so, then the slight PSNR drop for the test failures are expected, right? And we just need to rebase the reference PSNR?

This PR matches iHD driver however causes some quality regression when using i965 driver because 50 is not added in i965 driver.

**Comment by uartie** [comment]
I assume, then, that this patch won't be acceptable or submitted to upstream.  So I am closing this.

**Comment by xhaihao** [comment]
We need this for iHD at least, otherwise the quantization parameters written in the header in gstreamer-vaapi doesn't match the quantization parameters used in encoding process. How about adding a quirk for iHD in gstreamer-vaapi to calculate the quantization parameters?

**Comment by uartie** [comment]
I think a quirk would be acceptable.  You can submit a patch and see what @ceyusa thinks.

**Pull request closed without merging**
